name: Test
on:
  pull_request:
    branches:
      - master
      - develop
      - next
      - beta
      - alpha
    types:
      - opened
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies.
        run: pnpm install
      - name: Run tests.
        run: pnpm test
        env:
          CI: true